server:
  port: 8081

spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://localhost:5432/quizplatform_auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 saat (ms)
  refresh-expiration: 604800000 # 7 gün (ms)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
